"""
github_client.py
Handles all GitHub operations for the pipeline.
Creates feature branches, commits files,
and opens Pull Requests.

Rules:
  Never push directly to main or develop.
  Always target pipewright-staging.
  Branch names always include timestamp.
  Uses PyGithub library.
  All operations are synchronous.
  Credentials come from project record.
  Never log tokens - mask in all output.
"""

import re
from datetime import datetime, timezone
from pathlib import Path

from github import Github, GithubException

from backend.models.handoff import CoderHandoff, PatchResult


BRANCH_PREFIX = "pipewright"
DEFAULT_BASE_BRANCH = "pipewright-staging"
FORBIDDEN_BASE_BRANCHES = {"main", "master", "develop"}
MAX_BRANCH_LENGTH = 60


def _get_client(github_token: str) -> Github:
    """
    Create authenticated GitHub client.
    Raises RuntimeError if token is invalid.
    """
    try:
        client = Github(github_token)
        client.get_user().login
        return client
    except Exception as error:
        raise RuntimeError(
            f"github_client.py: Invalid GitHub token. error={error}"
        )


def _generate_branch_name(feature_description: str) -> str:
    """
    Generate a safe branch name from feature description.
    Format: pipewright/short-description-YYYYMMDD-HHMMSS
    Max 60 characters total.
    """
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    safe = re.sub(r"[^a-zA-Z0-9\s]", "", feature_description)
    words = safe.lower().split()[:5]
    short = "-".join(words) or "change"
    suffix = f"-{timestamp}"
    max_short_length = MAX_BRANCH_LENGTH - len(BRANCH_PREFIX) - 1 - len(suffix)
    short = short[:max_short_length].rstrip("-")
    return f"{BRANCH_PREFIX}/{short}{suffix}"


def _validate_base_branch(github_base_branch: str) -> str:
    try:
        base_branch = github_base_branch or DEFAULT_BASE_BRANCH
        if base_branch in FORBIDDEN_BASE_BRANCHES:
            raise RuntimeError(
                f"github_client.py: forbidden base branch: {base_branch}"
            )
        return base_branch
    except RuntimeError:
        raise
    except Exception as error:
        raise RuntimeError(f"github_client.py: failed to validate base branch: {error}")


def create_pull_request(
    github_token: str,
    github_owner: str,
    github_repo: str,
    github_base_branch: str,
    feature_description: str,
    coder_output: CoderHandoff,
    patch_result: PatchResult,
    diff: str,
    run_id: str,
    repo_path: str
) -> dict:
    """
    Create a GitHub PR for the approved pipeline run.

    Steps:
      1. Authenticate with GitHub
      2. Get the target repo
      3. Create a new branch from base_branch HEAD
      4. Commit all changed files to the new branch
      5. Open a PR from new branch to base_branch
      6. Return PR details

    Returns dict with:
      pr_url, pr_number, branch_name, status
    """
    base_branch = _validate_base_branch(github_base_branch)

    print(f"[GITHUB] Starting PR creation | run_id={run_id}")
    print(f"[GITHUB] Target: {github_owner}/{github_repo}")
    print(f"[GITHUB] Base branch: {base_branch}")

    try:
        client = _get_client(github_token)
        print("[GITHUB] Authenticated successfully")
    except Exception as error:
        raise RuntimeError(f"github_client.py: Auth failed. {error}")

    try:
        repo = client.get_repo(f"{github_owner}/{github_repo}")
        print(f"[GITHUB] Repo found: {repo.full_name}")
    except GithubException as error:
        raise RuntimeError(
            f"github_client.py: Repo not found. "
            f"{github_owner}/{github_repo} | error={error}"
        )

    branch_name = _generate_branch_name(feature_description)
    try:
        base_ref = repo.get_branch(base_branch)
        base_sha = base_ref.commit.sha
        repo.create_git_ref(
            ref=f"refs/heads/{branch_name}",
            sha=base_sha
        )
        print(f"[GITHUB] Branch created: {branch_name}")
    except GithubException as error:
        raise RuntimeError(
            f"github_client.py: Failed to create branch. "
            f"branch={branch_name} | error={error}"
        )

    target_repo = Path(repo_path)
    commit_message = (
        f"feat: {feature_description[:72]}\n\n"
        f"Generated by Pipewright\n"
        f"Run ID: {run_id}"
    )

    for file_change in coder_output.files_changed:
        file_path = file_change.path
        full_path = target_repo / file_path

        try:
            if file_change.action == "delete":
                try:
                    existing = repo.get_contents(
                        file_path, ref=branch_name
                    )
                    repo.delete_file(
                        file_path,
                        commit_message,
                        existing.sha,
                        branch=branch_name
                    )
                    print(f"[GITHUB] Deleted: {file_path}")
                except GithubException:
                    print(f"[GITHUB] File not on remote, skip delete: {file_path}")
                continue

            if not full_path.exists():
                print(f"[GITHUB] Warning: file missing on disk, skipping: {file_path}")
                continue

            content = full_path.read_text(encoding="utf-8")

            try:
                existing = repo.get_contents(
                    file_path, ref=branch_name
                )
                repo.update_file(
                    file_path,
                    commit_message,
                    content,
                    existing.sha,
                    branch=branch_name
                )
                print(f"[GITHUB] Updated: {file_path}")
            except GithubException:
                repo.create_file(
                    file_path,
                    commit_message,
                    content,
                    branch=branch_name
                )
                print(f"[GITHUB] Created: {file_path}")

        except Exception as error:
            raise RuntimeError(
                f"github_client.py: Failed to commit file. "
                f"path={file_path} | error={error}"
            )

    print(f"[GITHUB] All files committed to {branch_name}")

    pr_title = f"[Pipewright] {feature_description[:72]}"
    pr_body = (
        f"## Pipewright Auto-generated PR\n\n"
        f"**Feature:** {feature_description}\n\n"
        f"**Run ID:** `{run_id}`\n\n"
        f"**Files changed:**\n"
        + "\n".join(
            f"- `{file_change.path}` ({file_change.action})"
            for file_change in coder_output.files_changed
        )
        + f"\n\n**Summary:**\n{coder_output.summary}\n\n"
        f"**Diff:**\n```diff\n{diff[:3000]}\n```\n\n"
        f"---\n"
        f"*This PR was created automatically by Pipewright.*\n"
        f"*Review carefully before merging to main.*"
    )

    try:
        pr = repo.create_pull(
            title=pr_title,
            body=pr_body,
            head=branch_name,
            base=base_branch
        )
        print(f"[GITHUB] PR created: {pr.html_url}")
        print(f"[GITHUB] PR number: {pr.number}")

        return {
            "pr_url": pr.html_url,
            "pr_number": pr.number,
            "branch_name": branch_name,
            "base_branch": base_branch,
            "status": "created"
        }

    except GithubException as error:
        raise RuntimeError(
            f"github_client.py: Failed to create PR. error={error}"
        )
